### ISSUE TITLE
Information about the csv file used

### ISSUE THREAD

**Issue by shantanukarnwal** [EpistasisLab/MIMIC_trajectories#1]
Hi @brettbj . I am trying to replicate your unsupervised autoencoders code, and I was wondering how you created the "encounter_vectors_processed.csv" file, or maybe the fact that what does this file contain. I already have access to the MIMIC database, so answer to any one of these two questions would probably be sufficient for me to create a similar csv so that I could reimplement your code. Thanks!

**Comment by nitsanluke** [comment]
@brettbj @shakarnwal Were you able to find an answer to this? How can we create the `encounter_vectors_processed.csv`?

**Comment by christian-steinmeyer** [comment]
They create that specific file in [rocessEncounterVectors.ipynb](https://github.com/EpistasisLab/MIMIC_trajectories/blob/master/ProcessEncounterVectors.ipynb). But that only shifts the question to how they created `encounter_vectors.csv` and `mini_encounter_vectors.csv`. I'd also be interested in a response.

**Comment by sarwart** [comment]
Was anyone successful in creating `encounter_vectors.csv `and` mini_encounter_vectors.csv` files?
